### ISSUE TITLE
`tests/parsers/ebml` missing from sdist for 0.5.0

### ISSUE THREAD

**Issue by mgorny** [Diaoul/enzyme#40]
The sdist archive for 0.5.0 is missing the `tests/parsers/ebml` directory, which leads to test failures:

```pytb
____________________________________________________ EBMLTestCase.test_parse_full _____________________________________________________

self = <test_parsers.EBMLTestCase testMethod=test_parse_full>

    def setUp(self):
        self.stream = io.open(os.path.join(TEST_DIR, "test1.mkv"), "rb")
>       with io.open(os.path.join(EBML_VALIDATION_DIR, "test1.mkv.yml"), "r") as yml:
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/portage/dev-python/enzyme-0.5.0/work/enzyme-0.5.0/tests/parsers/e
bml/test1.mkv.yml'

self       = <test_parsers.EBMLTestCase testMethod=test_parse_full>

tests/test_parsers.py:27: FileNotFoundError
```

(and so on)

**Comment by Diaoul** [comment]
How is that possible :thinking:

**Comment by Diaoul** [comment]
Should be fixed in 0.5.1 :package:

**Comment by mgorny** [comment]
I'm afraid that didn't work. 0.5.1 is still missing that file.

**Comment by Diaoul** [comment]
Ah yes indeed, I focused on fixing `matroska.xml` that I broke when reworking the packaging 🤦

**Comment by Diaoul** [comment]
Released 0.5.2
